# Generated by Django 3.0.3 on 2020-03-15 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=4000)),
                ('texto', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('url', models.CharField(max_length=2000)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField()),
            ],
        ),
    ]
