# Generated by Django 3.0.3 on 2020-03-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='url',
            new_name='imagem_url',
        ),
    ]
