# Generated by Django 3.0.3 on 2020-04-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200404_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='produto',
            field=models.ManyToManyField(to='polls.Produto'),
        ),
        migrations.DeleteModel(
            name='CardapioProduto',
        ),
    ]
