# Generated by Django 3.0.3 on 2020-03-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
