# Generated by Django 3.0.3 on 2020-03-27 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200321_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=4000)),
                ('ordem', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CardapioProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(blank=True, default=None, null=True)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cardapio')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Produto')),
            ],
        ),
    ]
