# Generated by Django 3.0.3 on 2020-03-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200327_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='ordem',
        ),
    ]
